create table Person(
                       id int generated by default as identity primary key,
                       fullName varchar(100) not null UNIQUE,
                       yearOfBirth int not null
);

create table Book(
                     id int generated by default as identity primary key,
                     title varchar(100) not null,
                     person_id int REFERENCES Person(id) ON DELETE SET NULL,
                     author varchar(100) not null,
                     year int not null,
                     taken_at TIMESTAMP
);