create table Person(
    id int generated by default as identity primary key,
    fullName varchar(100) not null,
    yearOfBirth int not null
);

create table Book(
    id int generated by default as identity primary key,
    title varchar(100) not null,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    author varchar(100),
    year int not null
);